export const inputTokens = {
  height: "40px",
  paddingX: "12px",
  paddingY: "8px",
  gap: "8px",
  fontSize: "14px",
  lineHeight: "1.4",
  borderRadius: "8px",
  borderWidth: "1px",
  defaultBorderColor: "#d1d5db",
  focusBorderColor: "#2563eb",
  invalidBorderColor: "#dc2626",
  disabledBorderColor: "#e5e7eb",
  background: "#ffffff",
  disabledBackground: "#f3f4f6",
  readOnlyBackground: "#f9fafb",
  textColor: "#111827",
  placeholderColor: "#9ca3af",
  disabledTextColor: "#9ca3af",
  slotColor: "#6b7280",
  invalidSlotColor: "#dc2626",
  focusRingColor: "rgba(37, 99, 235, 0.2)",
  focusRingWidth: "3px",
  invalidRingColor: "rgba(220, 38, 38, 0.2)",
} as const;
