export const toggleGroupTokens = {
  gap: "0px",
  borderColor: "#d1d5db",
  borderRadius: "8px",
  paddingX: "12px",
  paddingY: "8px",
  fontSize: "14px",
  fontWeight: 500,
  lineHeight: "1.2",
  unselectedBackground: "#ffffff",
  unselectedColor: "#374151",
  unselectedHoverBackground: "#f3f4f6",
  selectedBackground: "#111827",
  selectedColor: "#ffffff",
  selectedHoverBackground: "#1f2937",
  focusRingColor: "#2563eb",
  focusRingWidth: "2px",
  disabledOpacity: 0.5,
} as const;
